---
# MySQL Deployment with Resource Requests
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.db.name }}
spec:
  selector:
    matchLabels:
      app: {{.Values.db.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.db.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-node1
      containers:
      - image: {{ .Values.db.image }}
        name: {{.Values.db.name }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-login
              key: mysql_root_pass  
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-login
              key: mysql_db
        ports:
        - containerPort: 3306
          name: {{.Values.db.name }}
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc 
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
